# Site settings
title: 魔都铮铮岁月
email: 384012351@qq.com
description: > # this means to ignore newlines until "baseurl:"
    wirte something to recording my coder's life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: 
github_username:  demanLiu

# Build settings
markdown: kramdown
paginate: 10
cate1: 网站设计
cate2: 大数据
cate3: 云计算
cate4: 基础运维
cate5: 生活随记
